# Copyright (C) 2013-2016 JadeCore <https://www.jadecore.tk/>
# Copyright (C) 2008-2016 TrinityCore <http://www.trinitycore.org/>
# Copyright (C) 2011-2016 Project SkyFire <http://www.projectskyfire.org/>
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

sudo: required
dist: trusty

language: cpp
compiler:
  - gcc

git:
  depth: 1

before_install:
  - sudo apt-get -qq install build-essential libtool make cmake cmake-data openssl
  - sudo apt-get -qq install libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev libace-dev
  - sudo apt-get -qq install mysql-server
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - mysql -uroot -e 'create database test_mysql;'
  - mkdir build
  - cd build
  - cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=0 -DSCRIPTS=1 -DSERVERS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=check_install
  - cd ..

script:
  - $CXX --version
  - mysql -uroot < data/sql/create/create_mysql.sql
  - cat sql/base/auth/*.sql | mysql -ujadecore -pjadecore auth
  - cat sql/base/characters/*.sql | mysql -ujadecore -pjadecore characters
  - cat sql/base/world/*.sql | mysql -ujadecore -pjadecore world
  - cat sql/updates/auth/5.4.7/*.sql | mysql -ujadecore -pjadecore auth
  - cat sql/updates/characters/5.4.7/*.sql | mysql -ujadecore -pjadecore characters
  - cat sql/updates/world/5.4.7/*.sql | mysql -ujadecore -pjadecore world
  - mysql -uroot < data/sql/create/drop_mysql.sql
  - cd build
  - make -j 8 -k && make install
  - cd check_install/build
